### ISSUE TITLE
Personal Information

### ISSUE THREAD

**Issue by hoke-t** [marcelvoss/WWDC15-Scholarship#1]
Just letting you know - if you want to censor personal info you should probably remove your town's coords from Constants.h

**Comment by marcelvoss** [comment]
Haha, it's already censored. The coordinates in the Constants.h are just placeholders. 😜

**Comment by hoke-t** [comment]
Haha alright, thought it might be just making sure! 😀 nice app though. 👍 I did not know about the scholarship opportunity this year but will hopefully be getting there next year!

**Comment by marcelvoss** [comment]
Thanks! Good luck next year! ☺️
